name: 'CI: API & E2E Test'

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  run_tests:
    name: API & E2E Test
    if: github.event.label.name == 'test ready'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials

    - name: Install openvpn3

    - name: Configure VPN credentials

    - name: VPN Connect

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'

    - name: Install newman & cypress
      run: npm install

    - name: API Test
      run: npm run ci:apitest

    - name: Upload API Test html report
      uses: actions/upload-artifact@v2
      with:
        name: htmlreport-apitest
        path: newman
        retention-days: 5

    - name: E2E Test
      run: npm run ci:endtoendtest:record
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    - name: Upload E2E Test video recording
      uses: actions/upload-artifact@v2
      with:
        name: videorecording-endtoendtest
        path: cypress/videos
        retention-days: 5
