name: 'CI: Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_api_tests:
    name: API
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run ci:apitest
    - uses: actions/upload-artifact@v2
      with:
        name: htmlreport-apitest
        path: newman
        retention-days: 5

  run_endtoend_tests:
    name: E2E
    runs-on: ubuntu-latest
    needs: [run_api_tests]

    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        record: true
        start: npm start
        wait-on: 'http://localhost:3000'
        spec: cypress/integration/todo.spec.js
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    - uses: actions/upload-artifact@v2
      with:
        name: videorecording-endtoendtest
        path: cypress/videos
        retention-days: 5
