# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'CI: Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_api_tests:
    name: API
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run ci:apitest
    - uses: actions/upload-artifact@v2
      with:
        name: htmlreport-apitest
        path: newman
        retention-days: 5

  run_endtoend_tests:
    name: E2E
    runs-on: ubuntu-latest
    needs: [run_api_tests]
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: npm install
    # - run: npm run ci:endtoendtest:record
    #   env:
    #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: npm start
        wait-on: 'http://localhost:3000'
        spec: cypress/integration/todo.spec.js
      env:
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: videorecording-endtoendtest
        path: cypress/videos
        retention-days: 5
