name: 'CI: API and E2E Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    name: Test Run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run ci:apitest
    - uses: actions/upload-artifact@v2
      with:
        name: htmlreport-apitest
        path: newman
        retention-days: 5
    - run: npm run ci:endtoendtest:record
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: videorecording-endtoendtest
        path: cypress/videos
        retention-days: 5
